### ISSUE TITLE
FEAT: Add Profile picture model

### ISSUE THREAD

**Issue by IsraelBO17** [codewitgabi/full-featured-social-media-application-fastapi#15]
Add profile picture model and create a one-to-many relationship between the user model and the profile picture model.

**Select all that apply**
We want to make sure this is feature
- [x] I have checked all `open` issues for this feature and it doesn't exist
- [x] I have checked all `closed` issues for this feature and it doesn't exist
- [x] This feature is relevant to the project.

**Comment by codewitgabi** [comment]
@IsraelBO17 user to profile picture should be a one to many relationship from the database design.

**Reason**
We want users to have history of profile pictures similar to what Facebook has. So when youadd a new DP, the previous one is not overwritten instead, a new one is added to them.

**Comment by IsraelBO17** [comment]
Alright Chief.
