### ISSUE TITLE
User Authentication Feature 

### ISSUE THREAD

**Issue by izzyjosh** [codewitgabi/full-featured-social-media-application-fastapi#53]
**Implementing user authentication for the project**

---

 User authentication is a very crucial aspect of any web app as it is charged with the duty of identifying users who are logged in or try to login 

---

We want to make sure this is a new feature

- [x] I have checked all `oen` issues for this feature and it doesn't exist
- [x] I have checked all `closed` issues for this feature and it doesn't exist
- [x] This feature is relevant to the project.

**Comment by codewitgabi** [comment]
- [ ] All issues must have the format `[ACTION]: message`. Where action can be one of [FEAT], [BUGFIX], [FIX] etc
- [ ] Leave headings for issue sections unless the entire section is not needed.
